package es

import "github.com/appbaseio-confidential/arc/internal/types/acl"

var (
	varRegexps = map[string]string{
		"{index}":                "[^_][^\\s/]*",
		"{type}":                 "[_]*[^\\s/]*",
		"{id}":                   "[^_][^\\s/]*",
		"{name}":                 "[^_][^\\s/]*",
		"{task_id}":              "[^_][^\\s/]*",
		"{scroll_id}":            "[^_][^\\s/]*",
		"{fields}":               "[^_][^\\s/]*",
		"{target}":               "[^_][^\\s/]*",
		"{metric}":               "[^_][^\\s/]*",
		"{alias}":                "[^_][^\\s/]*",
		"{new_index}":            "[^_][^\\s/]*",
		"{node_id}":              "[^_][^\\s/]*",
		"{repository}":           "[^_][^\\s/]*",
		"{thread_pool_patterns}": "[^_][^\\s/]*",
		"{index_metric}":         "[^_][^\\s/]*",
		"{context}":              "[^_][^\\s/]*",
		"{snapshot}":             "[^_][^\\s/]*",
	}

	categories = map[string]acl.ACL{
		"docs":     acl.Docs,
		"search":   acl.Search,
		"indices":  acl.Indices,
		"cat":      acl.Cat,
		"tasks":    acl.Clusters,
		"cluster":  acl.Clusters,
		"ingest":   acl.Misc,
		"snapshot": acl.Misc,
		"modules":  acl.Misc,
	}

	keywords = []string{
		"_cat",
		"_bulk",
		"_cluster",
		"_search",
		"_remote",
		"_create",
		"_count",
		"_scripts",
		"_doc",
		"_field_caps",
		"_source",
		"_explain",
		"_analyze",
		"_delete_by_query",
		"_cache",
		"_close",
		"_alias",
		"_aliases",
		"_template",
		"_flush",
		"_mapping",
		"_forcemerge",
		"_settings",
		"_open",
		"_upgrade",
		"_mappings",
		"_refresh",
		"_recovery",
		"_segments",
		"_rollover",
		"_split",
		"_shard_stores",
		"_shrink",
		"_ingest",
		"_stats",
		"_validate",
		"_mget",
		"_msearch",
		"_nodes",
		"_mtermvectors",
		"_rank_eval",
		"_reindex",
		"_update_by_query",
		"_render",
		"_snapshot",
		"_search_shards",
		"_tasks",
		"_update",
		"_termvectors",
	}
)
