apiVersion: v1
clusters:
  - cluster:
      certificate-authority-data: YOUR_CLUSTER_CERTIFICATE
      server: YOUR_CLUSTER_IP
    name: YOUR_CLUSTER_NAME
contexts:
  - context:
      cluster: YOUR_CLUSTER_NAME
      user: YOUR_CLUSTER_NAME
    name: YOUR_CLUSTER_NAME
current-context: YOUR_CLUSTER_NAME
kind: Config
preferences: {}
users:
  - name: YOUR_CLUSTER_NAME
    user:
      auth-provider:
        config:
          access-token: YOUR_ACCESS_TOKEN
          cmd-args: config config-helper --format=json
          cmd-path: CMD_PATH
          expiry-key: "{.credential.token_expiry}"
          token-key: "{.credential.access_token}"
        name: PROVIDER
