name: Send Build Image Event

on:
  release:
    types: [published]

jobs:
  determine_whether_to_run:
    runs-on: ubuntu-latest
    outputs:
      send_event: ${{ steps.check-send-event.outputs.run_jobs }}

    steps:
      - name: Check if event should be sent
        id: check-send-event
        run: (echo "${{ github.ref }}" | grep -Eq  '^refs\/tags\/[0-9]+\.[0-9]+\.[0-9]+$') && echo "::set-output name=run_jobs::true" || echo "::set-output name=run_jobs::false"

  send_event:
    needs: determine_whether_to_run
    runs-on: ubuntu-latest
    if: needs.determine_whether_to_run.outputs.send_event == 'true'

    steps:
      - name: Send Repo Dispatch Event
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          repository: appbaseio-confidential/elasticsearch-packer-build
          event-type: new_release
