name: Update Schema

on:
  push:
  release:
    types: [published]

jobs:
  send_build_event:
    runs-on: ubuntu-latest

    steps:
      - name: Send Repo Dispatch Event
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.token }}
          repository: appbaseio-confidential/arc-noss
          event-type: create_schema
