name: Update Schema

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Make clean and build
        run: make clean && make

      - name: Generate the latest schema
        run: ./build/reactivesearch --create-schema

      - name: Add and Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          add: schema
          default_author: github_actions
          message: Update schema according to latest release
          push: true
